stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:6.0-focal
  tags:
    - saas-linux-small-amd64
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - dotnet restore BLKSupportPortalDemo/BLKSupportPortalDemo.sln
    - dotnet build BLKSupportPortalDemo/BLKSupportPortalDemo.sln --configuration Release --no-restore
    - dotnet test BLKSupportPortalDemo/BLKSupportPortalDemo.sln --no-restore --verbosity normal


test-job2:
  stage: test
  script:
    - echo "This job tests something, but takes more time than test-job1."
    - echo "After the echo commands complete, it runs the sleep command for 20 seconds"
    - echo "which simulates a test that runs 20 seconds longer than test-job1"
    - sleep 20

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: production
